# Generated by Django 3.2.16 on 2022-10-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox22', '0004_auto_20221017_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='paradox22.Tag'),
        ),
    ]
