# Generated by Django 3.2.16 on 2022-10-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox22', '0005_auto_20221017_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
